# Generated by Django 3.2.16 on 2022-10-20 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(default='New List', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(default='new_list', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('name', models.CharField(default='', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(default='', unique=True)),
                ('quantity', models.CharField(default='1', max_length=5)),
                ('bought', models.BooleanField(default=False)),
                ('list_name', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.list')),
            ],
            options={
                'ordering': ['-bought'],
            },
        ),
    ]
