# Generated by Django 3.2.16 on 2022-11-18 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20221117_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(default='1', max_length=7),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default='New List', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(default='new_list', max_length=30, unique=True),
        ),
    ]
