# Generated by Django 3.2.16 on 2022-11-25 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20221118_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='list.list'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
