# Generated by Django 3.2.16 on 2022-10-14 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(default=('New List', models.DateField(default=django.utils.timezone.now)), max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='slug',
            field=models.CharField(default=('New List', models.DateField(default=django.utils.timezone.now)), max_length=50, unique=True),
        ),
    ]
